//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krooze.EntranceTest.WriteHere.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krooze.EntranceTest.WriteHere.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Cruises&gt;
        ///  &lt;AirMandatory&gt;false&lt;/AirMandatory&gt;
        ///  &lt;AllInclBnsCommTotal&gt;0.0&lt;/AllInclBnsCommTotal&gt;
        ///  &lt;AllInclBnsCommTotalBfrDisc&gt;0.0&lt;/AllInclBnsCommTotalBfrDisc&gt;
        ///  &lt;AllInclCommTotal&gt;1595.7&lt;/AllInclCommTotal&gt;
        ///  &lt;AllInclCommTotalBfrDisc&gt;1595.7&lt;/AllInclCommTotalBfrDisc&gt;
        ///  &lt;AllInclNetTotal&gt;10442.3&lt;/AllInclNetTotal&gt;
        ///  &lt;AllInclNetTotalBfrDisc&gt;10442.3&lt;/AllInclNetTotalBfrDisc&gt;
        ///  &lt;AllInclStdCommTotal&gt;1595.7&lt;/AllInclStdCommTotal&gt;
        ///  &lt;AllInclStdCommTotalBfrDisc&gt;1595.7&lt;/AllInclStdCommTotalBfrDisc&gt;
        ///  &lt;AllowedOccup [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cruises {
            get {
                return ResourceManager.GetString("Cruises", resourceCulture);
            }
        }
    }
}
